apiVersion: v1
kind: Service
metadata:
  name: msal-api-service
spec:
  selector:
    app: msal-api
  ports:
    - protocol: TCP
      port: 80 # The port the Service itself will expose
      targetPort: 8000 # The port on the Pods to forward traffic to
      # port: 8000 # The port the Service itself will expose
      # targetPort: 80 # The port on the Pods to forward traffic to
